name: Action-1
on: push
jobs:
  scm:
    runs-on: ubuntu-latest
    steps:
    - name: step-1
      run: hostnamectl
    - name: step-2
      run: pwd
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build-l
      run: echo "sheshivardhan"
